contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #umetaflow channel"
    url: https://nfcore.slack.com/channels/umetaflow
    about: Discussion about the nf-core/umetaflow pipeline
